version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  cognito-local:
    container_name: cognito-local
    image: jagregory/cognito-local:latest
    ports:
      - 9229:9229
    volumes:
      - .cognito:/app/.cognito